In [4]:
# import modules
from jrdb import load
from jrdb import parse

# load text data (ex. SED)
loader = load.FileLoader()
text_data = loader.load('data/SED_2022/SED220115.txt')

# parse
parser = parse.JrdbDataParser()
df = parser.parse(text_data, 'SED', is_japanese=True)   # return pandas DataFrame

In [5]:
df

,レースキー,場コード,年,回,日,R,馬番,競走成績キー,血統登録番号,年月日,...,天候コード,コース,レース脚質,単勝,複勝,本賞金,収得賞金,レースペース流れ,馬ペース流れ,4角コース取り
0,06221501,06,22,1,5,1,1,1910179520220115,19101795,20220115,...,1,None,4,None,None,0.0,0,33,33,1
1,06221501,06,22,1,5,1,2,1910659520220115,19106595,20220115,...,1,None,3,None,None,0.0,0,33,33,1
2,06221501,06,22,1,5,1,3,1910477420220115,19104774,20220115,...,1,None,3,None,None,0.0,0,33,33,3
3,06221501,06,22,1,5,1,4,1910624820220115,19106248,20220115,...,1,None,2,None,None,0.0,0,33,33,1
4,06221501,06,22,1,5,1,5,1910489820220115,19104898,20220115,...,1,None,4,None,None,0.0,0,33,33,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,10221112,10,22,1,1,12,14,1810312020220115,18103120,20220115,...,1,1,3,None,610,310.0,0,22,22,5
462,10221112,10,22,1,1,12,15,1710513220220115,17105132,20220115,...,1,1,2,None,None,0.0,0,22,33,3
463,10221112,10,22,1,1,12,16,1710485220220115,17104852,20220115,...,1,1,2,810,330,770.0,500,22,22,2
464,10221112,10,22,1,1,12,17,1810306320220115,18103063,20220115,...,1,1,2,None,None,0.0,0,22,33,3
465,10221112,10,22,1,1,12,18,1810282720220115,18102827,20220115,...,1,1,4,None,None,0.0,0,22,22,1